# Generated by Django 4.2 on 2025-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default='SOME STRING', upload_to='profiles/'),
        ),
    ]
